### ISSUE TITLE
Test set accuracy

### ISSUE THREAD

**Issue by lploumen** [amicks/Speculator#10]
Hi,
Do you manage to get a good test set accuracy with a relatively small delta (-d) ?
If you set a high delta, there's a good chance the next trend will be neutral isn't it ?

**Comment by amicks** [comment]
There is a higher chance of it being neutral, it's all a matter of what you want to be your "safety net".  You might want to not classify a $1 increase as a trend when a $20 increase might be a better indicator.  I ran a few tests and I'm getting 50-60% with d from 0 through 5.

**Comment by lploumen** [comment]
For BTC I presume ?

**Comment by amicks** [comment]
Yes, this was for USDT_BTC.  Did you have a specific symbol in mind?

**Comment by lploumen** [comment]
No. I did most of my tests with USDT_ETH (and a lower delta).
Which parameters do you use to get 60% of test set accuracy ?

**Comment by amicks** [comment]
I used the defaults in main.py.  Seeds are also randomized so you won't get exactly the same results.
