### ISSUE TITLE
Select best delta

### ISSUE THREAD

**Issue by binhvq** [amicks/Speculator#12]
How to select best delta when predict other coin ex: USDT_ZEC...

**Comment by amicks** [comment]
I'm not aware of any algorithm or formula to determine the best delta.  I would mess around with various deltas and see which produces good results on the test set.  Don't make the results on the test set too good though, just realistic.  Part of the delta is also personal preference.  What do you want your neutral boundaries to be when there are changes in price?  What's your risk aversion and how much are you willing to confidently say this is indicative of a trend?  There are a lot of factors at play.
