### ISSUE TITLE
python3 app.py

### ISSUE THREAD

**Issue by ghost** [amicks/Speculator#16]
Run python3 app.py on my mac.

And i got the following as output.

`
$ python3 app.py 
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from api import api, cache, ENABLE_DB, db
ModuleNotFoundError: No module named 'api'
`

Could you shed some light on how to bring up the rest service for btc/etc price predication please?

**Comment by amicks** [comment]
This is probably an issue with the repo not being in your PYTHONPATH environment variable, and not with the repo itself.

**Comment by samiashton1989** [comment]
how can i fix ??? No module named 'api'
