### ISSUE TITLE
Error Classification metrics can't handle a mix of continuous-multioutput and multiclass targets

### ISSUE THREAD

**Issue by lploumen** [amicks/Speculator#8]
Hi,
I followed the step to use Speculator, but when I run it, I got the error in the image below...
All files are original ones, I did not modify anything.

![image](https://user-images.githubusercontent.com/11539944/32173248-9f52951c-bd7e-11e7-8404-35cf201549c0.png)

**Comment by amicks** [comment]
Can you try it again and see if it's reproducible?  It sounds like Poloniex gave some strange HTTP response and it couldn't be parsed.  Can you also try with the --model dnn argument?  Thanks!

edit: I used virtualenv and couldn't reproduce it.  Judging by the traceback in line 42, the "accuracy_score(actual, preds)" line has changed in the most recent commit, so you are on an older version.  Can you do a git pull and see if the error still shows up?

**Comment by lploumen** [comment]
OK it is working, I had to reinstall speculator using pip.
Thank you
